
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: ["ttsNuance","asrNuance"],
  plugins: {
    ttsNuance: {
      pluginName: "ttsNuance",
      config: [
        /**
         * the environment(s) in which this plugin can/should be enabled
         * @default ["android", "ios"]
         */
        "env",
        /**
         * the plugin type
         * @default "tts"
         */
        "type",
        /**
         * the module/plugin name for the MediaManager plugins configuration
         * @default "mmir-plugin-speech-nuance/ttsNuance"
         */
        "mod"
      ],
      defaultValues: {
        env: ["android","ios"],
        type: "tts",
        mod: "mmir-plugin-speech-nuance/ttsNuance"
      },
      speechConfig: [
        /** OPTIONAL
         * a specific voice for TTS
         * @type string
         */
        "voice",
        /** OPTIONAL
         * the language/country for TTS
         * @type string
         */
        "language"
      ]
    },
    asrNuance: {
      pluginName: "asrNuance",
      config: [
        /**
         * the environment(s) in which this plugin can/should be enabled
         * @default ["android", "ios"]
         */
        "env",
        /**
         * the plugin type
         * @default "asr"
         */
        "type",
        /**
         * the module/plugin name for the MediaManager plugins configuration
         * @default "mmir-plugin-speech-nuance"
         */
        "mod"
      ],
      defaultValues: {
        env: ["android","ios"],
        type: "asr",
        mod: "mmir-plugin-speech-nuance"
      }
    }
  }
};
